#!/bin/bash

API_TOKEN="pk_82249628_UDCI4FKFA43QQFCNUJNKUSS4R9NMS4H7"
PARENT_TASK_ID="86b5xbbkx"
LIST_ID="901410635217"
PARENT_TASK_ID="86b5xbbkx"
API_URL="https://api.clickup.com/api/v2/list/$LIST_ID/task"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click Quire AI search field\", \"description\": \"Next, verify that \\\"Welcome to Quire AI Search\\\" shows. XPath: //div[contains(@class, 'ai-search-modal-body') and contains(., 'Welcome to Quire AI Search')]\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Enter prompt in Quire AI search field\", \"description\": \"Uses placeholder: Tell Quire AI what you're looking for...\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click Quire AI filter button\", \"description\": \"Opens filter options in Quire AI.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click Quire AI status field\", \"description\": \"Opens the status dropdown for filtering.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Confirm Quire AI status value\", \"description\": \"Verifies dropdown values: Writing, Ready for Review, In Review, Draft, Final, Final Locked.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click writing status dropdown\", \"description\": \"Selects Writing from the status dropdown.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click Quire AI search button\", \"description\": \"Initiates the search based on filters.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Hover over first search result\", \"description\": \"Simulates mouse hover on the first search result.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Confirm report opened in new tab\", \"description\": \"Verifies that clicking the result opens the report in a new browser tab.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click Ask Quire button\", \"description\": \"Opens the AI chat or question feature.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click AI chat back button\", \"description\": \"Navigates back in the AI chat interface.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Verify AI intro chat body\", \"description\": \"Ensures the introductory chat message is present.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click Quire AI continue conversation button\", \"description\": \"Continues the AI conversation.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Click Quire AI create summary button\", \"description\": \"Triggers AI to create a summary.\", \"parent\": \"86b5xbbkx\"}"

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data "{\"name\": \"Verify AI chat create summary response\", \"description\": \"Verifies the summary response generated by AI.\", \"parent\": \"86b5xbbkx\"}"


curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Enter prompt in Quire AI search field", "description": "Uses placeholder: Tell Quire AI what you\'re looking for..."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click Quire AI filter button", "description": "Opens filter options in Quire AI."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click Quire AI status field", "description": "Opens the status dropdown for filtering."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Confirm Quire AI status value", "description": "Verifies dropdown values: Writing, Ready for Review, In Review, Draft, Final, Final Locked."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click writing status dropdown", "description": "Selects Writing from the status dropdown."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click Quire AI search button", "description": "Initiates the search based on filters."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Hover over first search result", "description": "Simulates mouse hover on the first search result."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Confirm report opened in new tab", "description": "Verifies that clicking the result opens the report in a new browser tab."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click Ask Quire button", "description": "Opens the AI chat or question feature."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click AI chat back button", "description": "Navigates back in the AI chat interface."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Verify AI intro chat body", "description": "Ensures the introductory chat message is present."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click Quire AI continue conversation button", "description": "Continues the AI conversation."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Click Quire AI create summary button", "description": "Triggers AI to create a summary."}'

curl --request POST \
  --url "$API_URL" \
  --header "Authorization: $API_TOKEN" \
  --header "Content-Type: application/json" \
  --data '{"name": "Verify AI chat create summary response", "description": "Verifies the summary response generated by AI."}'
